const test = require("node:test");
const assert = require("node:assert/strict");
const { randomUUID } = require("node:crypto");
const mongoose = require("mongoose");
const { MongoMemoryReplSet } = require("mongodb-memory-server");
const models = require("../models/Listening");
const AlbumCatalog = require("../models/AlbumCatalog");
const { prepareSeedPlan, applySeedPlan } = require("../lib/listening/seeds");

test("mapping seed apply is exact, atomic, catalog-only identity binding with zero diary writes", { skip: process.env.RUN_MONGO_INTEGRATION !== "true" }, async (t) => {
  const repl = await MongoMemoryReplSet.create({ replSet: { count: 1 } });
  await mongoose.connect(repl.getUri(), { dbName: "listening_seeds_test" });
  t.after(async () => { await mongoose.disconnect(); await repl.stop(); });
  await Promise.all([AlbumCatalog, ...Object.values(models)].map((Model) => Model.init()));
  const album = await AlbumCatalog.create({ albumId: randomUUID(), title: "Standard", artistDisplayName: "Artist", catalogSource: "manual" });
  const binding = (name) => ({ artist: "Artist", album: name, albumId: album.albumId, reason: "Reviewed shared album identity", sources: ["https://example.org/release"] });
  const prepare = (bindings) => prepareSeedPlan({ bindings, environment: "test", fingerprint: "test", AlbumCatalog, ...models });
  const options = { reviewer: "operator", mongoose, AlbumCatalog, models };
  const plan = await prepare([binding("Deluxe"), binding("Expanded")]);
  await applySeedPlan(plan, options);
  assert.equal(await models.AlbumMapping.countDocuments(), 2);
  assert.equal(await models.MappingAudit.countDocuments(), 2);
  assert.equal(await models.Job.countDocuments({ type: "reprocess" }), 2);
  assert.equal(await AlbumCatalog.countDocuments(), 1);
  assert.equal((await AlbumCatalog.findById(album._id)).catalogRevision, 1);
  await assert.rejects(applySeedPlan(plan, options), /SEED_MAPPING_ALREADY_EXISTS/);
  assert.equal(await models.MappingAudit.countDocuments(), 2);
  const stale = await prepare([binding("New edition"), binding("Other edition")]);
  stale.entries[1].catalogRevision = 42;
  await assert.rejects(applySeedPlan(stale, options), /SEED_CATALOG_REVISION_CHANGED/);
  assert.equal(await models.AlbumMapping.countDocuments(), 2, "first entry rolled back when second failed");
  assert.equal(await models.MappingCase.countDocuments(), 2);
  for (const collection of ["listens", "boardlistens", "listencreations"]) assert.equal(await mongoose.connection.collection(collection).countDocuments(), 0);
});
